# Generated by Django 2.2.16 on 2022-09-18 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients_recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ingredient', models.CharField(max_length=200, unique=True)),
                ('description_ingredient', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='title_recipe',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ForeignKey(help_text='Выберите Tag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag', to='recipe.Tag', verbose_name='tag'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients_recipe',
            field=models.ForeignKey(help_text='Выберите ингредиент', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients_recipe', to='recipe.Ingredients_recipe', verbose_name='ingredients_recipe'),
        ),
    ]
