# Generated by Django 2.2.16 on 2022-09-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20220918_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients_recipe',
            name='unit_ingredient',
            field=models.CharField(default=3, max_length=20),
            preserve_default=False,
        ),
    ]
