# Generated by Django 2.2.16 on 2022-09-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20220927_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_recipe',
            field=models.ManyToManyField(help_text='Выберите ингредиент', through='recipe.Amount', to='recipe.Ingredients_recipe', verbose_name='ingredients_recipe'),
        ),
    ]
