# Generated by Django 2.2.16 on 2022-09-27 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20220927_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients_recipe',
            new_name='ingredient',
        ),
    ]
