# Generated by Django 2.2.16 on 2022-09-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_auto_20220927_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(through='recipe.Amount', to='recipe.Ingredients_recipe'),
        ),
    ]
