# Generated by Django 2.2.16 on 2022-09-27 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_auto_20220927_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients_recipe',
        ),
    ]
