version: '3.8'

services:
  db:
    # image: postgres:13.0-alpine
    image: amvmail/db_13.0-alpine:latest
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  backend:
      build:
        context: ../backend/foodgram
        dockerfile: Dockerfile
      restart: always
      volumes:
        - static_value:/code/static/
        - media_value:/code/media/
      depends_on:
        - db
      env_file:
        - ./.env
  frontend:
    image: amvmail/frontend:latest
    # build:
      # context: ../frontend
      # dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: amvmail/nginx_1_19_3:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  db_data:
  result_build:
  static_value:
  media_value: