version: '3.8'
services:
  frontend:  # сборка image
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/  # нужен ли тут диск?

  postgresql:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  django:
      image: amvmail/foodgram-project:latest
      restart: always
      volumes:
        - static_value:/app/static/
        - media_value:/app/media/
      depends_on:
        - postgresql
      env_file:
        - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - django

volumes:
  static_value:
  media_value: