# Generated by Django 3.2.4 on 2022-10-16 18:53

import recipes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='style',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='value',
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=10, null=True, verbose_name='цвет'),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=3, max_length=200, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to='recipes/', validators=[recipes.validators.image_size_validator], verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default=3, max_length=50, unique=True, verbose_name='название тега'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='amount',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 1)), name='quantity_gte_1'),
        ),
    ]
