# Generated by Django 3.2.4 on 2022-10-12 20:12

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to='recipes/', validators=[recipes.validators.image_size_validator], verbose_name='изображение'),
        ),
        migrations.AddConstraint(
            model_name='amount',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 1)), name='quantity_gte_1'),
        ),
    ]
