# Generated by Django 3.2.4 on 2022-10-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='amount',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 1)), name='quantity_gte_1'),
        ),
    ]
